In [133]:
!pip install numpy



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [134]:
import numpy as np

In [135]:
print(np.__version__)

2.4.3


In [136]:
## Creating Arrays

In [137]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [138]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [139]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [140]:
print(arr_list1.ndim)

1


In [141]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1  ,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [142]:
print(arr_list1_2.ndim)

2


In [143]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1  ,list2,list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [144]:
print(arr_list1_3.ndim)

3


In [13]:
## numpy array attribute

In [145]:
arr1 = np.array([[1,2,3] , [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [146]:
print("Shape" , arr1.shape)
print("Size" , arr1.size)
print("dType" , arr1.dtype)
print("n_dim" ,arr1.ndim)

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [147]:
## Array Initialization method

In [148]:
#zeros Array
zero_arr = np.zeros((2,3))
print(zero_arr )

[[0. 0. 0.]
 [0. 0. 0.]]


In [149]:
## one array
one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [150]:
## full array
full_arr = np.full((3,2),8)
print(full_arr)

[[8 8]
 [8 8]
 [8 8]]


In [151]:
id_arr =np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [152]:
## identify matrix 3 rows 3 colomn

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [153]:
##empty array
print(np.empty(2))

[9.9e-324 1.5e-323]


In [23]:
## Evenly Spaced Array
print(np.arange(1,10,2))

[1 3 5 7 9]


## Specefic Number of Equally (Speed) value between a range

In [154]:
print (np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [155]:
## random value array Float
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.75468847 0.11677354]
 [0.77300472 0.11008199]
 [0.89082376 0.73782703]]


In [156]:
## random value array int
rint_arr = np.random.randint(1,10,(3,3))
print(rint_arr)

[[3 1 9]
 [8 8 8]
 [1 6 5]]


In [157]:
#Array indexing and Slicing
a= np.array([1,2,3,4,5] )
print(a)

[1 2 3 4 5]


In [158]:
print(a[0])

1


In [159]:
print(a[1])

2


In [160]:
print(a[-1])

5


In [161]:
#Array indexing and Slicing
a= np.array([1,2,3,4,5] )
print(a)
# slicing [start: stop : stpe]
# stop  # input , that is not include in output 

[1 2 3 4 5]


In [162]:
print(a[0:3])   # first three element

[1 2 3]


In [163]:
print(a[-5:])

[1 2 3 4 5]


In [164]:
print(a[0:5:2]) # middle first element with steps

[1 3 5]


In [165]:
print(a[-3:])   # last  three element

[3 4 5]


In [166]:
print(a[-3:])

[3 4 5]


In [167]:
# Two dimention array
arr2 = np.array([[1,2,3] ,[4,5,6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [168]:
print(arr2[1][1])

5


In [169]:
print(arr2[1:])

[[4 5 6]]


In [170]:
print(arr2[1])

[4 5 6]


In [171]:
print(arr2[: ,2])

[3 6]


In [172]:
print(arr2[1][1])

5


In [173]:
print(arr2[: , 1])
# 2D : [Rows , columns]
# 3D : [Layers/Height , rows , columns]

[2 5]


In [174]:
print(arr2[0][0]) # elemnet of first rows first columns
print(arr2[0][1])# elemnet of first rows second columns
print(arr2[0][2])# elemnet of first rows third columns

1
2
3


In [175]:
print(arr2[0] )
print(arr2[1] )
      

[1 2 3]
[4 5 6]


In [176]:
arr3 = np.array([[1,2,3],
                 [2,3,4],
                 [5,6,7]])
print(arr3)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [177]:
print (arr3[0])
print (arr3[1])
print (arr3[2])

[1 2 3]
[2 3 4]
[5 6 7]


In [178]:
print(arr3[0][1])
print(arr3[0][2])
print(arr3[0][0])

2
3
1


In [179]:
print(arr3[ : , 2])

[3 4 7]


In [180]:
print(arr3[ : , 1])

[2 3 6]


In [181]:
print(arr3[ : , 0])

[1 2 5]


In [182]:
print(arr3 [::2,0])

[1 5]


In [183]:
print(arr3 [::3,0])

[1]


In [184]:
print(arr3[1:2, :1])

[[2]]


# Array Reshapping and  Flattening

In [185]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [186]:
reshape = arr1.reshape([6,1])
print(reshape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [187]:
reshaped1 = arr1.reshape([2,3])
print(reshaped1)

[[1 2 3]
 [4 5 6]]


In [188]:
reshaped2 = arr1.reshape([2 ,3])
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [189]:
print (reshaped2.flatten())

[1 2 3 4 5 6]


In [190]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


#Array Stacking and Spliting

In [191]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b))) # Verticle stackning in row
print(np.hstack((a,b))) # verticle stacking in columns

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [192]:
c = np.array([[1,2,3] , [4,5,6]])
print(c)


[[1 2 3]
 [4 5 6]]


In [193]:
print(np.hsplit(c ,3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [194]:
print(np.hsplit(c ,3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [195]:
c = np.array([[1,2,3] ,[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


split = np.hsplit(c , 3) # Horizontal split

 for s in vsplit:
   print(s)

In [196]:
#Mathematical Operation an Array

In [197]:
a = np.array([10 , 30 , 50 , -30])
print(a)

[ 10  30  50 -30]


In [198]:
print(a+10)
print(a-30)
print(a*2)
print(a/10)

[ 20  40  60 -20]
[-20   0  20 -60]
[ 20  60 100 -60]
[ 1.  3.  5. -3.]


In [199]:
a = np.array([1,4,9])
print(a)

[1 4 9]


In [200]:
print(np.square(a))
print(np.sqrt(a))

[ 1 16 81]
[1. 2. 3.]


In [201]:
# sin , cos, tan , sec

In [202]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))


[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]


In [203]:
#Mathematically Oepration in multiple array

In [204]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [205]:
print(np.add(a ,b))
print(np.subtract(a ,b))
print(np.divide(a ,b))
print(np.multiply(a ,b))

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]


In [206]:
print(np.dot(a,b))

32


In [207]:
print(a.T)

[1 2 3]


In [208]:
t = np.array([[1,2,3],
              [4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# Statistical function

In [209]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [210]:
print(np.sum(a))

21


In [211]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


# Array Camparision

In [212]:
a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [213]:
print(a == b)
print(np.array_equal(a,b))

[False  True False]
False


 # 11 Broadcasting

In [214]:
a = np.array([1,2,3,5])
b = np.array([5])
print(a+b)

[ 6  7  8 10]


In [215]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([10 , 20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


#12  Handling with nan and inf

In [218]:
data1 = np.array([1,2 ,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [221]:
print(np.isnan(data1))

[False False  True False False]


In [223]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


#Array Save and Load

In [225]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [226]:
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]
